### Group Names:
Cheah Jun Yitt WQD180107  
Choo Jian Wei WQD180124  
Choong En Jun WQD180113  
Tan Yin Yen WQD180108  

### Topic: 
Poverty

# Costa Rican Household Poverty Level Prediction
Refer to the following link for detailed information for each variable of the dataset:  
https://www.kaggle.com/c/costa-rican-household-poverty-prediction/data

## Data Cleaning Process 
### 7003 Data Analytics Online class (26/03/2019)

## Load Data

In [53]:
import pandas as pd
import numpy as np

df = pd.read_csv("Data/costa-rican-household-poverty-prediction/train.csv")
df.head()

,Id,v2a1,hacdor,rooms,hacapo,v14a,refrig,v18q,v18q1,r4h1,...,SQBescolari,SQBage,SQBhogar_total,SQBedjefe,SQBhogar_nin,SQBovercrowding,SQBdependency,SQBmeaned,agesq,Target
0,ID_279628684,190000.0,0,3,0,1,1,0,NaN,0,...,100,1849,1,100,0,1.000000,0.0,100.0,1849,4
1,ID_f29eb3ddd,135000.0,0,4,0,1,1,1,1.0,0,...,144,4489,1,144,0,1.000000,64.0,144.0,4489,4
2,ID_68de51c94,NaN,0,8,0,1,1,0,NaN,0,...,121,8464,1,0,0,0.250000,64.0,121.0,8464,4
3,ID_d671db89c,180000.0,0,5,0,1,1,1,1.0,0,...,81,289,16,121,4,1.777778,1.0,121.0,289,4
4,ID_d56d6f5f5,180000.0,0,5,0,1,1,1,1.0,0,...,121,1369,16,121,4,1.777778,1.0,121.0,1369,4

# Missing Values

In [52]:
missing = pd.isna(df).sum()
missing[missing > 0]

v2a1         6860
v18q1        7342
rez_esc      7928
meaneduc        5
SQBmeaned       5
dtype: int64

**Columns with missing values:**  
v2a1, Monthly rent payment  
v18q1, number of tablets household owns  
rez_esc, Years behind in school  
meaneduc,average years of education for adults (18+)  
SQBmeaned, square of the mean years of education of adults (>=18) in the household

**Solution:**
    - Create a new class "Unknown" for the first phase. 
    - Potentially impute a most probable value or feature mean   
    
*v2a1* - 6860 missing observations - Use mean  
*v18q1* - 7342 missing observations -  Replace missing value with zero  
*rez_esc* - 7928 missing observations - Suggest to remove this variable, as *escolari* variable, which means the years of *schooling* is sufficient to indicate a person’s education level  
*meaneduc* - 5 missing observations - Removing these observations are insignificant  
*SQBmeaned* - 5 missing observations - Removing these observations are insignificant

## Inconsistent Data

In [56]:
df[["edjefe", "edjefa"]].head()

  edjefe edjefa
0     10     no
1     12     no
2     no     11
3     11     no
4     11     no

- The same field which is stored as different values but indicates the same meaning.This would lead to inconsistencies.    
- For example:  
    1) For the ‘dependency’ column, the data are inconsistent. Some are ‘Yes’ ,’No’, while some are numeric values.  
        - Calculate the dependency rate using (hogar_mayor + hogar_nin)/(hogar_total)  
    2) For ‘edjefe’ and ‘edjefa’:  
        - Replace “yes” with 1  
        - Aggregate them to a single column to represent head of household years of education.  
        - If both are “no”, then the aggregated value should be 0.

## Duplicate Data
- Remove duplicate records  

## Outliers/wrong data
- Remove outliers
- Eg: Under “Age” column, there are a few 0s,1s,2s etc, This does not seems right. We can remove rows that are questionable.

## Data Transformation (Dealing with Noisy Data)
### Binning: 
- Easier to visualize data with binning. One of the major attributes is monthly rent payment. We can select equal-depth partitioning for the monthly rent payment

### Aggregation: 
- We can aggregate columns that ask the same thing but of different results
- E.g. These variables can be aggregate to only one column
    - Gender:
        - male 
        - female
    - Predominant material on the outside wall:
        - paredblolad, =1 if predominant material on the outside wall is block or brick
        - paredzocalo, "=1 if predominant material on the outside wall is socket (wood,  zinc or absbesto"
        - paredpreb, =1 if predominant material on the outside wall is prefabricated or cement
        - pareddes, =1 if predominant material on the outside wall is waste material
        - paredmad, =1 if predominant material on the outside wall is wood
        - paredzinc, =1 if predominant material on the outside wall is zink
        - paredfibras, =1 if predominant material on the outside wall is natural fibers
        - paredother, =1 if predominant material on the outside wall is other
    - Predominant material on the floor
        - pisomoscer, "=1 if predominant material on the floor is mosaic,  ceramic,  terrazo"
        - pisocemento, =1 if predominant material on the floor is cement
        - pisoother, =1 if predominant material on the floor is other
        - pisonatur, =1 if predominant material on the floor is  natural material
        - pisonotiene, =1 if no floor at the household
        - pisomadera, =1 if predominant material on the floor is wood
    - Predominant material on the roof
        - techozinc, =1 if predominant material on the roof is metal foil or zink
        - techoentrepiso, "=1 if predominant material on the roof is fiber cement,  mezzanine "
        - techocane, =1 if predominant material on the roof is natural fibers
        - techootro, =1 if predominant material on the roof is other
        - cielorazo, =1 if the house has ceiling
    - Water provision
        - abastaguadentro, =1 if water provision inside the dwelling
        - abastaguafuera, =1 if water provision outside the dwelling
        - abastaguano, =1 if no water provision
    - Electricity
        - public, "=1 electricity from CNFL,  ICE,  ESPH/JASEC"
        - planpri, =1 electricity from private plant
        - noelec, =1 no electricity in the dwelling
        - coopele, =1 electricity from cooperative
    - Toilet
        - sanitario1, =1 no toilet in the dwelling
        - sanitario2, =1 toilet connected to sewer or cesspool
        - sanitario3, =1 toilet connected to  septic tank
        - sanitario5, =1 toilet connected to black hole or letrine
        - sanitario6, =1 toilet connected to other system
    - Main source of energy
        - energcocinar1, =1 no main source of energy used for cooking (no kitchen)
        - energcocinar2, =1 main source of energy used for cooking electricity
        - energcocinar3, =1 main source of energy used for cooking gas
        - energcocinar4, =1 main source of energy used for cooking wood charcoal
    - Rubbish disposal
        - elimbasu1, =1 if rubbish disposal mainly by tanker truck
        - elimbasu2, =1 if rubbish disposal mainly by botan hollow or buried
        - elimbasu3, =1 if rubbish disposal mainly by burning
        - elimbasu4, =1 if rubbish disposal mainly by throwing in an unoccupied space
        - elimbasu5, "=1 if rubbish disposal mainly by throwing in river,  creek or sea"
        - elimbasu6, =1 if rubbish disposal mainly other
    - Walls condition
        - epared1, =1 if walls are bad
        - epared2, =1 if walls are regular
        - epared3, =1 if walls are good
    - Roof condition
        - etecho1, =1 if roof are bad
        - etecho2, =1 if roof are regular
        - etecho3, =1 if roof are good
    - Floor condition
        - eviv1, =1 if floor are bad
        - eviv2, =1 if floor are regular
        - eviv3, =1 if floor are good
    - Subject civil status
        - estadocivil1, =1 if less than 10 years old
        - estadocivil2, =1 if free or coupled union
        - estadocivil3, =1 if married
        - estadocivil4, =1 if divorced
        - estadocivil5, =1 if separated
        - estadocivil6, =1 if widow/er
        - estadocivil7, =1 if single
    - Subject household status
        - parentesco1, =1 if household head
        - parentesco2, =1 if spouse/partner
        - parentesco3, =1 if son/daughter
        - parentesco4, =1 if stepson/daughter
        - parentesco5, =1 if son/daughter in law
        - parentesco6, =1 if grandson/daughter
        - parentesco7, =1 if mother/father
        - parentesco8, =1 if father/mother in law
        - parentesco9, =1 if brother/sister
        - parentesco10, =1 if brother/sister in law
        - parentesco11, =1 if other family member
        - parentesco12, =1 if other non family member
    - Subject education level
        - instlevel1, =1 no level of education
        - instlevel2, =1 incomplete primary
        - instlevel3, =1 complete primary
        - instlevel4, =1 incomplete academic secondary level
        - instlevel5, =1 complete academic secondary level
        - instlevel6, =1 incomplete technical secondary level
        - instlevel7, =1 complete technical secondary level
        - instlevel8, =1 undergraduate and higher education
        - instlevel9, =1 postgraduate higher education
    - House ownership
        - tipovivi1, =1 own and fully paid house
        - tipovivi2, "=1 own,  paying in installments"
        - tipovivi3, =1 rented
        - tipovivi4, =1 precarious
        - tipovivi5, "=1 other(assigned,  borrowed)"
    - Region
        - lugar1, =1 region Central
        - lugar2, =1 region Chorotega
        - lugar3, =1 region PacÃƒ ­fico central
        - lugar4, =1 region Brunca
        - lugar5, =1 region Huetar AtlÃƒ ¡ntica
        - lugar6, =1 region Huetar Norte
    - Settlement
        - area1, =1 zona urbana
        - area2, =2 zona rural

## Data Reduction

- Feature Selection
- Remove columns that imply the other column. 
    - For these variables, 
        - hhsize, household size
        - r4h1, Males younger than 12 years of age
        - r4h2, Males 12 years of age and older
        - r4h3, Total males in the household
        - r4m1, Females younger than 12 years of age
        - r4m2, Females 12 years of age and older
        - r4m3, Total females in the household
        - r4t1, persons younger than 12 years of age
        - r4t2, persons 12 years of age and older
        - r4t3, Total persons in the household
        - tamhog, size of household
        - tamviv, number of persons living in the household

      They can be selected to include only r4h1, r4h2, r4m1 and r4m2, and tamhog, because:
        - r4h3 can be derived from r4h1 and r4h2
        - r4m3 can be derived from r4m1 and r4m2
        - r4t1, r4t2, r4t3 can be derived 
        - tamviv is likely to be irrelevant
        - male and female may have different roles in the family, so as the age; 
        size of household includes only the number of persons for whom a person is financially responsible (may not be the same as total persons in the household).

    - Include only dependency, and remove the rest from
        - hogar_nin, Number of children 0 to 19 in household
        - hogar_adul, Number of adults in household
        - hogar_mayor, # of individuals 65+ in the household
        - hogar_total, # of total individuals in the household
        - dependency, Dependency rate, calculated = (number of members of the household younger than 19 or older than 64)/(number of member of household between 19 and 64)

    - Remove mobilephone from:
        - mobilephone, =1 if mobile phone
        - qmobilephone, # of mobile phones

    - Remove squared values:
        - SQBescolari, escolari squared
        - SQBage, age squared
        - SQBhogar_total, hogar_total squared
        - SQBedjefe, edjefe squared
        - SQBhogar_nin, hogar_nin squared
        - SQBovercrowding, overcrowding squared
        - SQBdependency, dependency squared
        - SQBmeaned, square of the mean years of education of adults (>=18) in the household
        - agesq, Age squared